services:
  postgres:
    image: postgres:13.1
    container_name: asistencia-app
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=asistencia_app
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5439:5432